import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Fully explicit sidebar config (not filesystem-autogenerated).
 * Update this file when adding, renaming, or reordering docs pages.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'glossary',
    'changelog',
    'api',
    {
      type: 'category',
      label: 'Tools & Platforms',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'tools/best-tools',
      },
      items: [
        'tools/best-tools',
        'tools/newsletter-platforms',
        'tools/self-hosted-esp',
        'tools/email-builders',
        'tools/deliverability-tools',
        'tools/growth-automation-tools',
        'tools/email-service-providers',
        'tools/ecommerce',
        'tools/automation-platforms',
        'tools/email-work-tools',
        'tools/open-source-tools',
      ],
    },
    {
      type: 'category',
      label: 'Strategy & Growth',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'strategy/building-an-email-list',
      },
      items: [
        {
          type: 'category',
          label: 'Get started',
          collapsed: false,
          items: [
            'strategy/reasons-for-newsletters',
            'strategy/sending-frequency',
            'strategy/email-marketing-strategy',
          ],
        },
        {
          type: 'category',
          label: 'Grow your list',
          collapsed: false,
          items: [
            'strategy/building-an-email-list',
            'strategy/list-building-playbook',
            'strategy/opt-in-tactics',
            'strategy/lead-generation',
          ],
        },
        {
          type: 'category',
          label: 'Campaigns & lifecycle',
          collapsed: true,
          items: [
            'strategy/lifecycle-emails',
            'strategy/personalization',
            'strategy/data-driven',
            'strategy/cold-email-tips',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides & Articles',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'guides/why-email-matters',
      },
      items: [
        'guides/why-email-matters',
        'guides/read-later',
        'guides/email-templates',
        'guides/demand-curve',
        'guides/blogs',
        'guides/faq',
        {
          type: 'category',
          label: 'Vendor blogs',
          collapsed: true,
          items: [
            'guides/vendor-blogs/vero-insights',
            'guides/vendor-blogs/zapier',
            'guides/vendor-blogs/drip',
            'guides/vendor-blogs/automizy',
            'guides/vendor-blogs/revue',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Development',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'development/frontend-development',
      },
      items: [
        'development/frontend-development',
        'development/html-email-tutorials',
        'development/html-email-templates',
        'development/github-repositories',
        'development/related-repositories',
        'development/cool-projects',
        'development/html-utilities',
        'development/checkers',
      ],
    },
    {
      type: 'category',
      label: 'Operations & Metrics',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'operations/dns-dkim',
      },
      items: [
        'operations/gdpr',
        'operations/administration',
        'operations/dns-dkim',
        'operations/amazon-ses',
        {
          type: 'category',
          label: 'Metrics & measurement',
          collapsed: true,
          link: {
            type: 'doc',
            id: 'operations/metrics/index',
          },
          items: [
            'operations/metrics/email-marketing-basics',
            'operations/metrics/measure-performance',
            'operations/metrics/effective-email-marketing',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'More',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'more/transactional-emails',
      },
      items: [
        'more/transactional-emails',
        'more/services',
        'more/arthur-tkachenko',
        'more/awesome-lists',
        'more/similar-companies',
        'more/miscellaneous',
        'more/additional-content',
      ],
    },
  ],
};

export default sidebars;
